require("impatient")

require("user.plugins")
require("user.options")
require("user.autocmds")
require("user.theme")
require("user.mappings")
require("user.config")
require("user.noice")
require("user.bufferline")
require("user.lsp")
require("user.treesitter")
require("user.telescope")
